### ISSUE TITLE
SPIKE -- Investigate Cleaner Ways to Generate & Integrate Sitemap Work

### ISSUE THREAD

**Issue by mbarnett** [ualbertalib/Hydranorth2#73]
We will need to bring forward our sitemap work for google scholar, while also taking this opportunity to clean up and simplify some of the logic in our approach.

Currently we use the rails-sitemap gem to generate a static set of sitemap files, periodically re-run by a cron job. There's another gem out there that, to my eyes, is a little easier to use: https://github.com/kjvarga/sitemap_generator

As part of the cleanup we could move any remaining properties into Solr to avoid the need to reify fedora objects in the current implementation, potentially speeding up the sitemap generation process.

Our current implementation includes collections, so maintaining this in the forward porting should satisfy the collection requirements in the new epic. 

We might want to consider moving this functionality to a small utility gem for community use.

**Comment by mbarnett** [comment]
- SPIKE: figure out a cleaner way to do the sitemap stuff (drive everything off of Solr (current implementation is a pre-generated set of files off of a rake task) and do it live w/ caching) -- 8
- Implementation

**Comment by pbinkley** [comment]
Bear in mind that the digitized materials could expand the sitemap dramatically, so we might end up with concerns about Solr load (though it's the fastest part of our stack) and want to fall back on a cached sitemap. Building the cached version from Solr rather than Fedora would still be a win though. The benefit of giving the crawlers an up-to-the-minute sitemap aren't likely to be that big compared to a nightly cached version.
